### ISSUE TITLE
Android: crash on pop/goBack

### ISSUE THREAD

**Issue by Hirbod** [react-navigation/navigation-ex#247]
Newest version, ejected from expo, Alpha Screen Version 22.
Cross-Posting, since I don't know if the error is caused by screens or navigation-ex. Please close if not related to this package.

https://github.com/kmagiera/react-native-screens/issues/266

When I have a TabStack, and the screen implements another native Stack with 2 screens, following both screens and pressing backbutton 2 times to return to my main tab, the app crashes.

```
```bash
Process: com.nummernschild, PID: 8759
01-05 20:56:32.695  8759  8759 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.app.AppCompatActivity.setSupportActionBar(androidx.appcompat.widget.Toolbar)' on a null object reference
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at com.swmansion.rnscreens.ScreenStackHeaderConfig.onUpdate(ScreenStackHeaderConfig.java:135)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at com.swmansion.rnscreens.ScreenStackHeaderConfig.onAttachedToWindow(ScreenStackHeaderConfig.java:70)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.View.dispatchAttachedToWindow(View.java:19553)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3430)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5149)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:4935)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:4875)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:4848)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:887)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2100)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1874)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

```tsx

            <NavigationNativeContainer>
                <Root.Navigator
                    screenOptions={{
                        headerShown: false,
                        headerTintColor: 'white',
                        headerLargeTitle: true,
                        headerStyle: {backgroundColor: '#b7cd23'},
                    }}
                >
                    {
                        props.app.authToken && true && props.app.authToken !== "" ? (
                            <>
                                <Stack.Screen name="Home" component={tabStack} />
                                <Stack.Screen options={{
                                    presentation: "push",
                                    headerShown: true,
                                    title: "Chat",
                                    headerLargeTitle: false
                                }} name="Message" component={Message}/>
                                <Stack.Screen options={{
                                    presentation: "modal",
                                    headerShown: false,
                                    title: "User",
                                    headerLargeTitle: false
                                }} name="User" component={User}/>
                            </>
                        ) : (
                            <Stack.Screen name="Login" component={Login} />
                        )
                    }
                </Root.Navigator>
            </NavigationNativeContainer>
```

...

```tsx
                <Tab.Screen
                    name="Chats"
                    component={chatStack}
                    options={{
                        tabBarBadge: props.app.user.plates.length && props.app.unreadMessages > 0 ? props.app.unreadMessages : false,
                        tabBarLabel: 'Chats',
                        tabBarIcon: ({color, size = 25}) => (
                            <Entypo style={{height: 30, width: 30}} name="chat" color={color} size={size}/>
                        ),
                    }}
                />
```

```
const chatStack = () => {
    const Stack = createNativeStackNavigator();
    return React.useMemo(() => {
        return (
            <Stack.Navigator
                screenOptions={{
                    headerShown: true,
                    headerTintColor: 'white',
                    headerLargeTitle: true,
                    headerStyle: {backgroundColor: '#b7cd23'},
                }}
            >
                <Stack.Screen name="Messages" options={{title: "Chats"}} component={Messages}/>
            </Stack.Navigator>
        );
    },[]);
};
```

Inside the ChatStack, I open another modal which is defined in the rootStack. This one causes the crash.

**Comment by Hirbod** [comment]
A video might help
https://youtu.be/ZUvV_kkuOXo

**Comment by satya164** [comment]
Unrelated to your issue, but this is a weird way of making a component. Just do this:

```js
const Stack = createNativeStackNavigator();

const chatStack = () => {
  return (
    <Stack.Navigator>
      ...
    </Stack.Navigator>
  );
};
```

**Comment by Hirbod** [comment]
1) that’s a lot of test code and not final and the order isn’t right pasted
2) I had to use react memo since I’ve connected my redux store directly to the tab navigator in order to get my badge counter 
3) I’ve connected redux to my root navigator to determine logged in or not. 

With memo every single props change cause d my whole app to re render. Therefore I can’t see anything weird tbh

**Comment by satya164** [comment]
You're not supposed to call createStackNavigator inside a component. As per the docs it needs to be outside.

Also component names should start with uppercase letter like `ChatStack`, not `chatStack`. It's works fine here because React Navigation internally handles the component creation and it doesn't care about variable name, but it won't work you want to use it like a normal component in JSX.

> I had to use react memo since I’ve connected my redux store directly to the tab navigator in order to get my badge counter

I don't see why that would require wrapping elements of an entirely different component in `useMemo`. Your usage of badge is in a tab navigator, the stack navigator where you have `useMemo` is inside a screen in the tabs which doesn't care about what props you use above.

> Without memo every single props change caused my whole app to re render.

That's not true. React Navigation already prevents unnecessary renders for each screen by using `React.memo` internally. This extra `useMemo` is unnecessary.

> Therefore I can’t see anything weird tbh

You're supposed to wrap your component `React.memo` for optimizations, not wrap elements inside a component in `useMemo`. Have you ever seen `React.useMemo` used like this in React docs?

**Comment by Hirbod** [comment]
You want me to record a video showing how my app is reloading 4000 times a minute without memo? But this was fixed since I wrapped the root in the memo (which I haven’t in my Code example). You might be right that using memo on all the other stacks is not needed, but it was for the root. 

Thanks for the other hints, I’ll refactor once I have something stable running.

**Comment by satya164** [comment]
> You want me to record a video showing how my app is reloading 4000 times a minute without memo? But this was fixed since I wrapped the root in the memo

I'm talking about `ChatStack`, which is not root since it's inside a tab from the code you posted. Regardless, if your component is re-rendering 4000 times, there are other issues, but also unless that 4000 times re-render is actually caused by React Navigation, it's not going to re-render you `ChatStack` as React Navigation already wraps it in `React.memo` internally (unless there's a bug in React Navigation).

**Comment by Hirbod** [comment]
No, it was re-rendering the RootStack. (which was fixed adding useMemo). So I assumed, adding it on every Stack is an good idea. I'll change that, thanks! 

So shall I also remove useMemo on the RootStack component?
```tsx
const AppStack = (props) => {

    const Stack = createNativeStackNavigator();
    const Root = createNativeStackNavigator();

    return React.useMemo(() => {

        return (
            <NavigationNativeContainer>
                <Root.Navigator
                    screenOptions={{
                        headerShown: false,
                        headerTintColor: 'white',
                        headerLargeTitle: true,
                        headerStyle: {backgroundColor: '#b7cd23'},
                    }}
                >
                    {
                        props.app.authToken && true && props.app.authToken !== "" ? (
                            <>
                                <Stack.Screen name="Home" component={tabStack} />
                                <Stack.Screen options={{
                                    presentation: "push",
                                    headerShown: true,
                                    title: "Chat",
                                    headerLargeTitle: false
                                }} name="Message" component={Message}/>
                                <Stack.Screen options={{
                                    presentation: "modal",
                                    headerShown: false,
                                    title: "User",
                                    headerLargeTitle: false
                                }} name="User" component={User}/>
                            </>
                        ) : (
                            <Stack.Screen name="Login" component={Login} />
                        )
                    }
                </Root.Navigator>
            </NavigationNativeContainer>
        );

    }, [props.app.authToken]);
};
```

and just wrap React.memo() on the export?

**Comment by satya164** [comment]
Yes, use `React.memo` on the export, not on children.

**Comment by Hirbod** [comment]
I totally removed all the usage of React.memo and nothing is flickering.. Not sure if one of the Alpha Updates fixed something but its running fine.. Thanks!

This is my "playground" btw.

```tsx
import * as React from "react";
import {Platform} from "react-native";
import {NavigationNativeContainer} from "@react-navigation/native";
import {createNativeStackNavigator} from "@react-navigation/native-stack";
import {createBottomTabNavigator} from "@react-navigation/bottom-tabs";
import { createMaterialBottomTabNavigator } from '@react-navigation/material-bottom-tabs';

import { MaterialCommunityIcons, Entypo } from '@expo/vector-icons';

import Profile from "../../src/social/Profile";
import Timeline from "../../src/social/Timeline";
import Messages from "../../src/social/Messages";
import User from "../../src/social/User";
import Message from "../../src/social/Message";
import EditProfile from "../../src/social/EditProfile";
import Account from "../../src/social/Account";
import EditAccount from "../../src/social/EditAccount";
import Blocked from "../../src/social/Blocked";
import AddCar from "../../src/social/Car/AddCar";
import SelectVehicle from "../../src/social/Car/SelectVehicle";
import SelectMake from "../../src/social/Car/SelectMake";
import SelectModel from "../../src/social/Car/SelectModel";
import SelectType from "../../src/social/Car/SelectType";
import SelectEngine from "../../src/social/Car/SelectEngine";
import SelectPicture from "../../src/social/Car/SelectPicture";
import Login from "../../src/login/Login";
import {connect} from 'react-redux';


const chatStack = () => {
    const Stack = createNativeStackNavigator();
    return React.useMemo(() => {
        return (
            <Stack.Navigator
                screenOptions={{
                    headerShown: true,
                    headerTintColor: 'white',
                    headerLargeTitle: true,
                    headerStyle: {backgroundColor: '#b7cd23'},
                }}
            >
                <Stack.Screen name="Messages" options={{title: "Chats"}} component={Messages}/>
            </Stack.Navigator>
        );
    },[]);
};

const UserScreen = createNativeStackNavigator();
const UserStack = () => {
    return (
        <UserScreen.Navigator
            screenOptions={{
                headerShown: true,
                headerTintColor: 'white',
                headerLargeTitle: true,
                headerStyle: {backgroundColor: '#b7cd23'},
            }}
        >
            <UserScreen.Screen name="User" options={{title: "Chats"}} component={User}/>
            <UserScreen.Screen options={{
                presentation: "push",
                headerShown: true,
                title: "Chat",
                headerLargeTitle: false
            }} name="Message" component={Message}/>
        </UserScreen.Navigator>
    );
};

const TimelineStack = createNativeStackNavigator();
const timelineStack = () => {
    return (
        <TimelineStack.Navigator
            screenOptions={{
                headerShown: true,
                headerTintColor: 'white',
                headerLargeTitle: true,
                headerStyle: {backgroundColor: '#b7cd23'},
            }}
        >
            <TimelineStack.Screen
                options={{title: "Entdecken"}}
                name="Timeline"
                component={Timeline} />

            <TimelineStack.Screen options={{
                presentation: "modal",
                headerShown: false,
                title: "User",
                headerLargeTitle: true
            }} name="User" component={Platform.OS === "android" ? User : UserStack} />
        </TimelineStack.Navigator>
    );
};

const Stack = createNativeStackNavigator();
const profileStack = () => {
    return (
        <Stack.Navigator
            screenOptions={{
                headerShown: true,
                headerTintColor: 'white',
                headerLargeTitle: true,
                headerStyle: {backgroundColor: '#b7cd23'},
            }}
        >
            <Stack.Screen name="Profile" options={{title: "Einstellungen"}} component={Profile}/>
            <Stack.Screen name="EditProfile"
                          options={{headerBackTitle: "Einst.", headerLargeTitle: false, title: "Profil bearbeiten"}}
                          component={EditProfile}/>

            <Stack.Screen name="AddCar"
                          options={{headerBackTitle: "Einst.", headerLargeTitle: false, title: "Kennzeichen"}}
                          component={AddCar}/>
            <Stack.Screen name="SelectVehicle"
                          options={{headerBackTitle: "Zurück", headerLargeTitle: false, title: "Fahrzeugtyp"}}
                          component={SelectVehicle}/>
            <Stack.Screen name="SelectMake" options={{headerLargeTitle: false, title: "Marke"}}
                          component={SelectMake}/>
            <Stack.Screen name="SelectModel" options={{headerLargeTitle: false, title: "Model"}}
                          component={SelectModel}/>
            <Stack.Screen name="SelectType" options={{headerLargeTitle: false, title: "Typ"}}
                          component={SelectType}/>
            <Stack.Screen name="SelectEngine" options={{headerLargeTitle: false, title: "Motor"}}
                          component={SelectEngine}/>
            <Stack.Screen name="SelectPicture" options={{headerLargeTitle: false, title: "Fast geschafft"}}
                          component={SelectPicture}/>


            <Stack.Screen name="Account"
                          options={{headerBackTitle: "Einst.", headerLargeTitle: false, title: "Account"}}
                          component={Account}/>
            <Stack.Screen name="EditAccount" options={{headerLargeTitle: false, title: "Bearbeiten"}}
                          component={EditAccount}/>
            <Stack.Screen name="Blocked" options={{headerLargeTitle: false, title: "Blockiert"}}
                          component={Blocked}/>

        </Stack.Navigator>
    );
};

const Tab = createMaterialBottomTabNavigator();
const TabBar = (props) => {
    const hasPlate = props.app.user && props.app.user.plates && props.app.user.plates.length > 0;
    return (
        <Tab.Navigator
            keyboardHidesNavigationBar={Platform.OS === "android"}
            initialRouteName="Chats"
            activeColor="#b7cd23"
            barStyle={{backgroundColor: '#f5f5f5'}}>

            <Tab.Screen
                name="Timeline"
                component={timelineStack}
                options={{
                    tabBarLabel: 'Entdecken',
                    tabBarIcon: ({color, size = 25}) => (
                        <MaterialCommunityIcons name="newspaper" color={color} size={size}/>
                    ),
                }}
            />
            <Tab.Screen
                name="Chats"
                component={chatStack}
                options={{
                    tabBarBadge: props.app.user.plates.length && props.app.unreadMessages > 0 ? props.app.unreadMessages : false,
                    tabBarLabel: 'Chats',
                    tabBarIcon: ({color, size = 25}) => (
                        <Entypo style={{height: 30, width: 30}} name="chat" color={color} size={size}/>
                    ),
                }}
            />
            <Tab.Screen
                name="Profile"
                component={profileStack}
                options={{
                    tabBarLabel: 'Einstellungen',
                    tabBarIcon: ({color, size = 25}) => (
                        <MaterialCommunityIcons name="settings" color={color} size={size}/>
                    ),
                }}
            />
        </Tab.Navigator>
    );
};
const TabStack = connect(state => ({app: state}))(TabBar);


const RootStack = createNativeStackNavigator();
const Root = createNativeStackNavigator();
const AppStack = (props) => {
    return (
        <NavigationNativeContainer>
            <Root.Navigator
                screenOptions={{
                    headerShown: false,
                    headerTintColor: 'white',
                    headerLargeTitle: true,
                    headerStyle: {backgroundColor: '#b7cd23'},
                }}
            >
                {
                    props.app.authToken && true && props.app.authToken !== "" ? (
                        <>
                            <RootStack.Screen name="Home" component={TabStack} />
                            <RootStack.Screen options={{
                                presentation: "push",
                                headerShown: true,
                                title: "Chat",
                                headerLargeTitle: false
                            }} name="Message" component={Message}/>
                            <RootStack.Screen options={{
                                presentation: "modal",
                                headerShown: false,
                                title: "User",
                                headerLargeTitle: false
                            }} name="User" component={User}/>
                        </>
                    ) : (
                        <RootStack.Screen name="Login" component={Login} />
                    )
                }
            </Root.Navigator>
        </NavigationNativeContainer>
    );
};

function arePropsEqual(prevProps, nextProps) {
    return prevProps.app.authToken === nextProps.app.authToken;
}

const AppWithNavigation = connect(state => ({app: state}))(AppStack);
export default AppWithNavigation;
```

**Comment by Hirbod** [comment]
Looks like I don't even need memo anymore. No re-renderings happen anymore. Totally weird.. Thanks for your help man!

**Comment by myckhel** [comment]
I remember when I had similar issue when using react-navigation 5 with bare react native

I fixed the issue by modifying proguard file

But in this case
You won't be able to modify any proguard file
Because its an expo project.
